### PR TITLE
Few Fixes and change to fxmanifest

### PR DESCRIPTION
**Pull request by FBFezz**

### CODE REVIEW

**Comment by FBFezz** [comment]
Me and Mycroft (my dev) have fixed the revive on the menu as well as changing the fxmanifest

**Comment by FBFezz** [comment]
Fixed the Mugshot not working

**Comment by Ozneeee** [comment]
Good job ✔️

I think I'll update the menu in a few weeks

**Comment by FBFezz** [comment]
Yeah its just fixes to the main issues we found while using the menu, would recommend trying to add a way for onesync infinite to use it

**Pull request closed without merging**
